name: '基金买卖预测自动运行'

on:
  schedule:
    - cron: '0 8 * * *'  # 每天UTC时间8:00运行(北京时间16:00)
  workflow_dispatch:  # 允许手动触发

jobs:
  predict:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write
      
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_TOKEN }}
          
      - name: 设置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: 安装Python依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: 运行基金预测
        run: python fund_prediction.py
        
      - name: 提交预测结果
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          
          # 检查是否有变更
          if [ -z "$(git status --porcelain)" ]; then
            echo "无变更可提交"
            exit 0
          fi
          
          git add models/fund_predictor.pkl
          git commit -m "自动更新基金预测模型 $(date +'%Y-%m-%d')"
          git push origin main